/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp.empresasgui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;


/**
 *
 * @author Joaco
 */

public class VistaEmpresas extends javax.swing.JFrame{

    private Component datos;

    

        
    /**
     * Creates new form VistaEmpresas
     */
    public VistaEmpresas() {
        this.empresas = new ArrayList<>();
        this.listaDeEmpleados = new ArrayList<>();
        initComponents();
        /*listaDeEmpleados = new ArrayList<>();*/
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtDocumento = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtSueldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcEmpresa = new javax.swing.JComboBox<>();
        jcCategoria = new javax.swing.JComboBox<>();
        jBMostrarEmpleado = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbCrearEmpresa = new javax.swing.JButton();
        jtRazonSocial = new javax.swing.JTextField();
        jtCuit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Documento");

        jtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocumentoActionPerformed(evt);
            }
        });

        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jLabel3.setText("Apellido");

        jLabel4.setText("Nombre");

        jLabel5.setText("Sueldo");

        jLabel6.setText("Empresa");

        jcEmpresa.setToolTipText("");

        jcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Jefe", "Administrativo" }));

        jBMostrarEmpleado.setText("Mostrar Empleados");
        jBMostrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBMostrarEmpleadoMouseClicked(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(jtNombre))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtApellido)
                                    .addComponent(jcCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jcEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jtSueldo)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jBMostrarEmpleado)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBGuardar)
                .addGap(174, 174, 174))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap(126, Short.MAX_VALUE)
                    .addComponent(jtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBMostrarEmpleado)
                    .addComponent(jBGuardar))
                .addGap(25, 25, 25))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );

        jLabel7.setText("Ingrese Datos");

        jInternalFrame2.setVisible(true);

        jLabel8.setText("Razon Social");

        jLabel9.setText("CUIT");

        jbCrearEmpresa.setText("Crear Empresa");
        jbCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(69, 69, 69)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jtCuit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jbCrearEmpresa)
                .addGap(121, 121, 121))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jbCrearEmpresa)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel10.setText("Ingrese Datos");

        jDesktopPane1.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(77, 77, 77)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jInternalFrame2))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu1.setText("Empleado");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Empresa");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sueldo");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Empresa> empresas;
    private ArrayList<Empleado> listaDeEmpleados;
    
    private Empresa buscarEmpresa(String razonSocial) {
        for (Empresa empresa : empresas) {
            if (empresa.getRazonSocial().equals(razonSocial)) {
                return empresa;
            }
        }
        return null;
    }
    
    private void jtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocumentoActionPerformed

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void jbCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearEmpresaActionPerformed
        // TODO add your handling code here:
        try{ 
            String razonSocial= jtRazonSocial.getText();
        String cuit = jtCuit.getText();
        int cuitInt = Integer.parseInt(cuit);
       
       Empresa empresa = new Empresa (razonSocial, cuitInt );
      empresas.add(empresa);
      jcEmpresa.addItem(empresa.getRazonSocial());
       
         JOptionPane.showMessageDialog(this, "La Carga se realizo con exito");       
        }catch(NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "El Cuit debe ser un numero");
            
            
        }
        jtRazonSocial.setText("");
        jtCuit.setText("");

    }//GEN-LAST:event_jbCrearEmpresaActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
          
        try {
        String dni = jtDocumento.getText();
        String nombre = jtNombre.getText();
        String apellido = jtApellido.getText();
        String categoria = (String) jcCategoria.getSelectedItem();
        String empresa = (String) jcEmpresa.getSelectedItem();
        String sueldo = (String) jtSueldo.getText();

        Empleado empleado = new Empleado(dni, nombre, apellido, categoria, empresa, sueldo, listaDeEmpleados);
        
        listaDeEmpleados.add(empleado);
        

        
        System.out.println("Empleado guardado:");
        System.out.println("DNI: " + dni);
        System.out.println("Nombre: " + nombre);
        System.out.println("Apellido: " + apellido);
        System.out.println("Categoría: " + categoria);
        System.out.println("Empresa: " + empresa);
        System.out.println("Sueldo: " + sueldo);

        JOptionPane.showMessageDialog(this, "Empleado guardado");

        jtDocumento.setText("");
        jtNombre.setText("");
        jtApellido.setText("");
        jcCategoria.setSelectedItem(null); // Limpia el combo box
        jcEmpresa.setSelectedItem(null); // Limpia el combo box
        jtSueldo.setText("");
    } catch (NumberFormatException nf) {
        JOptionPane.showMessageDialog(this, "Ingrese el Sueldo", "Error", JOptionPane.INFORMATION_MESSAGE);
    }








//        try{
//                String dni = jtDocumento.getText();
//                String nombre = jtNombre.getText();
//                String apellido = jtApellido.getText();
//                String categoria = (String) jcCategoria.getSelectedItem();
//                String empresa = (String) jcEmpresa.getSelectedItem();
//                String sueldo = (String) jtSueldo.getText();
//
//                Empleado nvoEmpleado = new Empleado(dni, nombre, apellido, categoria, empresa, sueldo, listaDeEmpleados);
//
//            
//            JOptionPane.showMessageDialog(this, "empleado guardado");
//           
//            jtDocumento.setText("");
//            jtNombre.setText("");
//            jtApellido.setText("");
//            jcCategoria.setSelectedItem(null); // Limpia el combo box
//            jcEmpresa.setSelectedItem(null); // Limpia el combo box
//            jtSueldo.setText("");
//        } catch (NumberFormatException nf){
//        JOptionPane.showMessageDialog(this, "ingrese numeros en el campo sueldo");
//        }
//        
//        
        
//       String empresaSeleccionada = (String) jcEmpresa.getSelectedItem();
//       String empresa = (String) jcEmpresa.getSelectedItem();
//
//        String dni = jtDocumento.getText();
//        String nombre = jtNombre.getText();
//        String apellido = jtApellido.getText();
//        String categoria = (String) jcCategoria.getSelectedItem();
//       // String empresa = (String) jcEmpresa.getSelectedItem();
//        double sueldo = Double.parseDouble(jtSueldo.getText());
        


        
       //Empleado empleado = new Empleado(dni, nombre, apellido, categoria, sueldo,empresa);
    
       
        
    
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBMostrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMostrarEmpleadoMouseClicked
      
    // Obtener la empresa seleccionada
    String empresaSeleccionada = (String) jcEmpresa.getSelectedItem();

    // Buscar la empresa seleccionada en la lista de empresas
    Empresa empresa = buscarEmpresa(empresaSeleccionada);

    if (empresa != null) {
        // Obtener la lista de empleados asociados a la empresa
        ArrayList<Empleado> empleadosEmpresa = empresa.getEmpleados();
        

        if (!empleadosEmpresa.isEmpty()) {
            // Mostrar un cuadro emergente para seleccionar un empleado de la empresa
            String[] empleadosNombres = new String[empleadosEmpresa.size()];
            for (int i = 0; i < empleadosEmpresa.size(); i++) {
                empleadosNombres[i] = empleadosEmpresa.get(i).getNombre() + " " + empleadosEmpresa.get(i).getApellido();
            }

            String empleadoSeleccionado = (String) JOptionPane.showInputDialog(this, "Selecciona un empleado:", "Empleados de " + empresa.getRazonSocial(), JOptionPane.PLAIN_MESSAGE, null, empleadosNombres, empleadosNombres[0]);

            // Buscar el empleado seleccionado
            Empleado empleado = null;
            for (Empleado emp : empleadosEmpresa) {
                if ((emp.getNombre() + " " + emp.getApellido()).equals(empleadoSeleccionado)) {
                    empleado = emp;
                    break;
                }
            }

            // Mostrar los datos del empleado seleccionado
            if (empleado != null) {
                String mensaje = "Nombre: " + empleado.getNombre() + "\n" +
                                 "Apellido: " + empleado.getApellido() + "\n" +
                                 "Categoría: " + empleado.getCategoria() + "\n" +
                                 "Sueldo: " + empleado.getSueldo() + "\n" +
                                 "Empresa: " + empleado.getEmpresa();

                JOptionPane.showMessageDialog(this, mensaje, "Datos del Empleado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay empleados registrados para esta empresa.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "La empresa seleccionada no existe.", "Error", JOptionPane.ERROR_MESSAGE);
    }


                                                 
//    // Obtener los valores de los campos de entrada
//    String nombre = jtNombre.getText();
//    String apellido = jtApellido.getText();
//    String categoria = (String) jcCategoria.getSelectedItem();
//    String sueldoStr = jtSueldo.getText();
//    String empresaSeleccionada = (String) jcEmpresa.getSelectedItem();
//    
//    try {
//        // Convertir el sueldo a double
//        double sueldo = Double.parseDouble(sueldoStr);
//        
//        // Buscar la empresa seleccionada en la lista de empresas
//        Empresa empresa = buscarEmpresa(empresaSeleccionada);
//        
//        // Crear un nuevo empleado con los datos ingresados
//        Empleado empleado = new Empleado(nombre, apellido, categoria, sueldo, empresa);
//        
//        // Mostrar un cuadro emergente con los datos del empleado
//        String mensaje = "Nombre: " + empleado.getNombre() + "\n" +
//                         "Apellido: " + empleado.getApellido() + "\n" +
//                         "Categoría: " + empleado.getCategoria() + "\n" +
//                         "Sueldo: " + empleado.getSueldo() + "\n" +
//                         "Empresa: " + empleado.getEmpresa();
//        
//        JOptionPane.showMessageDialog(this, mensaje, "Datos del Empleado", JOptionPane.INFORMATION_MESSAGE);
//        
////        // Limpiar los campos de entrada
////        jtNombre.setText("");
////        jtApellido.setText("");
////        jtSueldo.setText("");
//    } catch (NumberFormatException e) {
//        // Manejar una excepción si el sueldo no es un número válido
//        JOptionPane.showMessageDialog(this, "El sueldo debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
//    } catch (NullPointerException e) {
//        // Manejar una excepción si la empresa seleccionada no se encuentra en la lista de empresas
//        JOptionPane.showMessageDialog(this, "La empresa seleccionada no existe.", "Error", JOptionPane.ERROR_MESSAGE);
//    }
//


//String empresaCbox=(String) jcEmpresa.getSelectedItem();
//        if(empresaCbox != null && !empresaCbox.isEmpty()){
//                String dato = "";
//                for (Empleado empleado: listaDeEmpleados){
//                    if (empleado.getEmpresa().equals(empresaCbox)) {
//                        dato += "DNI: " + empleado.getDni() + "\n";
//                        dato += "Nombre y Apellido: " + empleado.getNombre() + " " + empleado.getApellido() + "\n";
//                        dato += "Categoría: " + empleado.getCategoria() + "\n";                        
//                        dato += "Sueldo: " +empleado.getSueldo();
//           }
//                    JOptionPane.showMessageDialog(this, dato, "Empleado de: " + empresaCbox, JOptionPane.INFORMATION_MESSAGE);
//        }
////                if(!dato.isEmpty()){
////                    JOptionPane.showMessageDialog(this, dato, "empleado de: " + empresaCbox, JOptionPane.INFORMATION_MESSAGE);
////                }else{
////                    JOptionPane.showMessageDialog(datos, "Esta empresa no tiene empleados");
////                }
////        }else{
////            JOptionPane.showMessageDialog(datos, "Seleccione Una Empresa");
//        }
//
//        
//              
            
         
        
    }//GEN-LAST:event_jBMostrarEmpleadoMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaEmpresas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBMostrarEmpleado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbCrearEmpresa;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JComboBox<String> jcEmpresa;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCuit;
    private javax.swing.JTextField jtDocumento;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtRazonSocial;
    private javax.swing.JTextField jtSueldo;
    // End of variables declaration//GEN-END:variables


}
